"""Make a self-contained, offline visual review page with the actual release font."""
from pathlib import Path
import base64,json,html
from fontTools.ttLib import TTFont
ROOT=Path(__file__).resolve().parents[1]
f=TTFont(ROOT/'fonts/ttf/SirenandSailor-Regular.ttf');cmap=f.getBestCmap()
b64=base64.b64encode((ROOT/'fonts/woff2/SirenandSailor-Regular.woff2').read_bytes()).decode()
ttf=base64.b64encode((ROOT/'fonts/ttf/SirenandSailor-Regular.ttf').read_bytes()).decode()
cells=''.join(f'<div class="glyph"><span>{html.escape(chr(c))}</span><small>U+{c:04X}</small></div>' for c in sorted(cmap) if c not in [32,160,0x200B,0x200C,0x200D,0x2028,0x2029,0x2060,0xFEFF])
page='''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Siren&Sailor — Font review</title><style>
@font-face{font-family:Siren;src:url(data:font/woff2;base64,FONTDATA) format('woff2');font-display:block}*{box-sizing:border-box}body{margin:0;background:#f8f4ea;color:#152d34;font:16px/1.55 system-ui,sans-serif}main{max-width:1280px;margin:auto;padding:38px 36px 80px}.eyebrow{text-transform:uppercase;letter-spacing:.18em;font-size:11px;color:#886b40}.title{font:clamp(64px,11vw,140px)/1.6 Siren;margin:24px 0 0}header{border-bottom:1px solid #c8c8b8;padding-bottom:24px}header p{max-width:650px;color:#526669;margin-top:0}nav{display:flex;gap:10px;flex-wrap:wrap;margin:25px 0}button,.download{font:inherit;font-size:13px;padding:9px 14px;border:1px solid #aeb8ae;background:transparent;border-radius:100px;cursor:pointer;color:inherit;text-decoration:none}button:hover{background:#e4e5da}.download{background:#152d34;color:#f8f4ea;border-color:#152d34}label{font-size:13px;color:#53676a}textarea{width:100%;min-height:110px;border:1px solid #b7c0b6;border-radius:5px;background:#fffdf8;padding:15px;font:16px/1.6 system-ui;color:#152d34;resize:vertical}.controls{display:flex;gap:28px;align-items:center;flex-wrap:wrap;margin:18px 0}.controls label{display:flex;align-items:center;gap:10px}input[type=range]{accent-color:#847045}.preview{font:100px/1.65 Siren;white-space:pre-wrap;overflow-wrap:anywhere;min-height:370px;padding:28px 4px 45px;font-kerning:normal}.divider{margin-top:25px;border-top:1px solid #c8c8b8;padding-top:30px}.sample{font:48px/1.7 Siren;overflow-wrap:anywhere}.samples small{color:#617271}details{margin-top:28px}summary{cursor:pointer;padding:14px 0;font-size:14px}.grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(110px,1fr));gap:8px}.glyph{border:1px solid #d8dacd;min-height:130px;padding:10px;display:flex;flex-direction:column;align-items:center;justify-content:space-between}.glyph span{font:55px/1.55 Siren}.glyph small{font-size:10px;color:#70817c}.fine{font-size:12px;color:#657770;max-width:900px}body.dark{background:#132c33;color:#f8f4ea}body.dark header p,body.dark label,body.dark .fine,body.dark small{color:#bbc8bf}body.dark button{border-color:#61746c}body.dark .download{background:#f8f4ea;color:#152d34}body.dark textarea{background:#203c43;color:#f8f4ea;border-color:#61746c}@media(max-width:600px){main{padding:24px 18px}.preview{font-size:65px}.controls{gap:15px}.sample{font-size:34px}}
</style><main><header><div class="eyebrow">Jean-Marc Dykes · Regular · Release candidate 1.000</div><h1 class="title">Siren & Sailor</h1><p>A nautical display serif with swept terminals, sharp hooks and a life of its own. Explore the extended alphabet, accents, figures and symbols below.</p><a class="download" download="SirenandSailor-Regular.ttf" href="data:font/ttf;base64,TTFDATA">Download review font</a></header><nav aria-label="Text samples"><button data-sample="Siren & Sailor\nA gentle tide at the quay.">The original</button><button data-sample="Café, façade, blåbær, cœur, Straße.\nPříliš žluťoučký kůň. Ģimene, ķīlis.">Accents & languages</button><button data-sample="0123456789\n$125.00  £249.00  €360.00  ₹780\n“Ready?” ‘Aye!’ ¡Sí! ¿Qué tal?">Figures & punctuation</button><button id="theme">Light / dark</button></nav><label for="words">Your text</label><textarea id="words" spellcheck="false">Siren & Sailor
A gentle tide at the quay.</textarea><div class="controls"><label>Size <input id="size" type="range" min="24" max="180" value="100"><output id="sizeOut">100 px</output></label><label>Spacing <input id="spacing" type="range" min="-2" max="10" step=".25" value="0"><output id="spacingOut">0 px</output></label><label><input type="checkbox" id="tnum">Tabular figures</label></div><div id="preview" class="preview" aria-live="polite"></div><section class="divider samples"><div class="eyebrow">Character study</div><p class="sample">ABCDEFGHIJKLMNOPQRSTUVWXYZ<br>abcdefghijklmnopqrstuvwxyz<br>0123456789 & $ £ € ¥ ₹<br>ÀÁÂÃÄÅ ÆÇÈÉÊË ÌÍÎÏÑÒÓÔÕÖØ ŒÙÚÛÜÝŸ<br>àáâãäå æçèéêë ìíîïñòóôõöø œùúûüýÿ ßẞ</p><small>Designed for titles, covers, signage and other display settings. Zero preserves the capital O outline.</small></section><details><summary>View all CHARS encoded characters</summary><div class="grid">CELLS</div></details><p class="fine divider">Menu name: Siren and Sailor. Branding: Siren&Sailor. This review file embeds the actual font and works offline. Prepared for a proposed SIL Open Font License release; public release and Google submission have not been performed. Full source, QA results and submission notes are in the accompanying package.</p></main><script>
const words=document.querySelector('#words'),preview=document.querySelector('#preview'),size=document.querySelector('#size'),spacing=document.querySelector('#spacing'),tnum=document.querySelector('#tnum');function update(){preview.textContent=words.value;preview.style.fontSize=size.value+'px';preview.style.letterSpacing=spacing.value+'px';preview.style.fontVariantNumeric=tnum.checked?'tabular-nums':'proportional-nums';document.querySelector('#sizeOut').textContent=size.value+' px';document.querySelector('#spacingOut').textContent=spacing.value+' px'}[words,size,spacing,tnum].forEach(x=>x.addEventListener('input',update));document.querySelectorAll('[data-sample]').forEach(x=>x.onclick=()=>{words.value=x.dataset.sample;update()});document.querySelector('#theme').onclick=()=>document.body.classList.toggle('dark');update();</script></html>'''
page=page.replace('FONTDATA',b64).replace('TTFDATA',ttf).replace('CELLS',cells).replace('CHARS',str(len(cmap)))
(ROOT/'proofs/SirenAndSailor-Type-Tester.html').write_text(page)
print('Wrote offline tester')
